on: [ push ]

name: FBAlves Lint
jobs:
  php-cs-fixer:
    name: PHP
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: PHP-CS-Fixer
        uses: falves97/php-cs-fixer-action@v1.0.1-beta